# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('apiname', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AchievementOwned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved', models.TextField(default='No')),
                ('apiname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements_owned', to='steamapp.Achievement')),
            ],
        ),
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communityBanned', models.BooleanField(default=False)),
                ('VACBanned', models.BooleanField(default=False)),
                ('numberOfVACBans', models.IntegerField(default=0)),
                ('daysSinceLastBan', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('appid', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GameOwned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeplayed_forever', models.IntegerField(default=0)),
                ('timeplayed_lastweek', models.IntegerField(default=0)),
                ('appid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_owned', to='steamapp.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('steamid', models.TextField(primary_key=True, serialize=False)),
                ('nickname', models.TextField()),
                ('profileurl', models.TextField()),
                ('privacity', models.TextField(blank=True, null=True)),
                ('currentstate', models.TextField(blank=True, null=True)),
                ('lastlog', models.DateField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='gameowned',
            name='steamid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_owned', to='steamapp.Player'),
        ),
        migrations.AddField(
            model_name='ban',
            name='steamid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='steamapp.Player'),
        ),
        migrations.AddField(
            model_name='achievementowned',
            name='steamid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements_owned', to='steamapp.Player'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='appid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='steamapp.Game'),
        ),
    ]
