# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steamapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AchievementOwned',
            new_name='OwnedAchivement',
        ),
        migrations.RenameModel(
            old_name='GameOwned',
            new_name='OwnedGame',
        ),
    ]
