# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamapp', '0002_auto_20160407_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='currentstate',
        ),
        migrations.RemoveField(
            model_name='player',
            name='privacity',
        ),
        migrations.AddField(
            model_name='player',
            name='privacy',
            field=models.TextField(default='private'),
        ),
        migrations.AddField(
            model_name='player',
            name='state',
            field=models.TextField(default='offline'),
        ),
        migrations.AlterField(
            model_name='player',
            name='lastlog',
            field=models.IntegerField(),
        ),
    ]
