# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamapp', '0004_auto_20160407_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='lastlog',
            field=models.IntegerField(),
        ),
    ]
