# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamapp', '0006_auto_20160407_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='state',
        ),
        migrations.AddField(
            model_name='player',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
    ]
