# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamapp', '0007_auto_20160407_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownedgame',
            name='timeplayed_lastweek',
        ),
        migrations.AddField(
            model_name='ownedgame',
            name='gamename',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownedgame',
            name='nickname',
            field=models.TextField(blank=True, null=True),
        ),
    ]
