# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steamapp', '0009_auto_20160408_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownedgame',
            name='appid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steamapp.Game'),
        ),
        migrations.AlterField(
            model_name='ownedgame',
            name='steamid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steamapp.Player'),
        ),
    ]
