# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steamapp', '0010_auto_20160408_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='name',
            new_name='displayname',
        ),
        migrations.AddField(
            model_name='achievement',
            name='namegame',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ownedgame',
            name='appid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownedgames', to='steamapp.Game'),
        ),
        migrations.AlterField(
            model_name='ownedgame',
            name='steamid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ownedgames', to='steamapp.Player'),
        ),
    ]
