# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steamapp', '0011_auto_20160408_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnedAchievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.TextField(blank=True, null=True)),
                ('gamename', models.TextField(blank=True, null=True)),
                ('achieved', models.TextField(default='No')),
                ('apiname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements_owned', to='steamapp.Achievement')),
                ('appid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements_owned', to='steamapp.Game')),
                ('steamid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements_owned', to='steamapp.Player')),
            ],
        ),
        migrations.RemoveField(
            model_name='ownedachivement',
            name='apiname',
        ),
        migrations.RemoveField(
            model_name='ownedachivement',
            name='steamid',
        ),
        migrations.DeleteModel(
            name='OwnedAchivement',
        ),
        migrations.AlterUniqueTogether(
            name='ownedachievement',
            unique_together=set([('steamid', 'apiname')]),
        ),
    ]
