# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamapp', '0012_auto_20160409_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='ban',
            name='nickname',
            field=models.TextField(blank=True, null=True),
        ),
    ]
