# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steamapp', '0013_ban_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownedgame',
            name='appid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gamesownedby', to='steamapp.Game'),
        ),
    ]
