# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steamapp', '0017_auto_20160415_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownedachievement',
            name='achid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievementsownedby', to='steamapp.Achievement'),
        ),
        migrations.AlterField(
            model_name='ownedachievement',
            name='steamid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownedachievements', to='steamapp.Player'),
        ),
    ]
