# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 12:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('steamapp', '0019_auto_20160509_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownedgame',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
