# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steamapp', '0023_auto_20160517_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='namegame',
            new_name='gamename',
        ),
    ]
