# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamapp', '0025_gamereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamereview',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five')], default=3, verbose_name='Rating (stars)'),
        ),
    ]
